-- MySQL Script generated by MySQL Workbench
-- Sun Apr  6 20:09:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS BaseDatosFundacion;
USE BaseDatosFundacion;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema basedatosfundacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basedatosfundacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basedatosfundacion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `basedatosfundacion` ;

-- -----------------------------------------------------
-- Table `basedatosfundacion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedatosfundacion`.`usuario` (
  `numDoc` VARCHAR(45) NOT NULL,
  `tipoDoc` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `nombre` TIMESTAMP NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numDoc`, `tipoDoc`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `basedatosfundacion`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedatosfundacion`.`asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `institucionEducativa` VARCHAR(45) NOT NULL,
  `fechaAsistencia` DATETIME NOT NULL,
  `Usuario_numDoc` VARCHAR(45) NOT NULL,
  `Usuario_tipoDoc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  UNIQUE INDEX `idAsistencia_UNIQUE` (`idAsistencia` ASC) VISIBLE,
  INDEX `fk_Asistencia_Usuario_idx` (`Usuario_numDoc` ASC, `Usuario_tipoDoc` ASC) VISIBLE,
  CONSTRAINT `fk_Asistencia_Usuario`
    FOREIGN KEY (`Usuario_numDoc` , `Usuario_tipoDoc`)
    REFERENCES `basedatosfundacion`.`usuario` (`numDoc` , `tipoDoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `basedatosfundacion`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedatosfundacion`.`estudiantes` (
  `numDoc` VARCHAR(45) NOT NULL,
  `tipoDoc` VARCHAR(45) NOT NULL,
  `primerNombre` VARCHAR(30) NOT NULL,
  `segundoNombre` VARCHAR(30) NULL DEFAULT NULL,
  `primerApellido` VARCHAR(32) NOT NULL,
  `segundoApellido` VARCHAR(32) NULL DEFAULT NULL,
  `genero` VARCHAR(2) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `grupoEtnico` VARCHAR(45) NOT NULL,
  `factorVulnerabilidad` VARCHAR(45) NOT NULL,
  `paisNacimiento` VARCHAR(45) NOT NULL,
  `municipioNacimiento` VARCHAR(45) NOT NULL,
  `municipioResidencia` VARCHAR(45) NOT NULL,
  `direccionResidencia` VARCHAR(45) NOT NULL,
  `zonaEstudiante` VARCHAR(45) NOT NULL,
  `mundo` VARCHAR(45) NOT NULL,
  `modalidad` VARCHAR(45) NOT NULL,
  `dias` VARCHAR(45) NOT NULL,
  `horarioInicio` VARCHAR(45) NOT NULL,
  `horarioFin` VARCHAR(45) NOT NULL,
  `codigoDaneIE` VARCHAR(45) NOT NULL,
  `subregionIE` VARCHAR(45) NULL,
  `municipioIE` VARCHAR(45) NOT NULL,
  `InstitucionEducativa` VARCHAR(45) NOT NULL,
  `codigoDaneSede` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  `grado` VARCHAR(2) NOT NULL,
  `jornada` VARCHAR(2) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numDoc`, `tipoDoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `basedatosfundacion`.`asistencia_has_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedatosfundacion`.`asistencia_has_estudiantes` (
  `Asistencia_idAsistencia` INT NOT NULL,
  `Estudiantes_numDoc` VARCHAR(45) NOT NULL,
  `Estudiantes_tipoDoc` VARCHAR(45) NOT NULL,
  `asistio` TINYINT NOT NULL,
  PRIMARY KEY (`Asistencia_idAsistencia`, `Estudiantes_numDoc`, `Estudiantes_tipoDoc`),
  INDEX `fk_Asistencia_has_Estudiantes_Estudiantes1_idx` (`Estudiantes_numDoc` ASC, `Estudiantes_tipoDoc` ASC) VISIBLE,
  INDEX `fk_Asistencia_has_Estudiantes_Asistencia1_idx` (`Asistencia_idAsistencia` ASC) VISIBLE,
  CONSTRAINT `fk_Asistencia_has_Estudiantes_Asistencia1`
    FOREIGN KEY (`Asistencia_idAsistencia`)
    REFERENCES `basedatosfundacion`.`asistencia` (`idAsistencia`),
  CONSTRAINT `fk_Asistencia_has_Estudiantes_Estudiantes1`
    FOREIGN KEY (`Estudiantes_numDoc` , `Estudiantes_tipoDoc`)
    REFERENCES `basedatosfundacion`.`estudiantes` (`numDoc` , `tipoDoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
